<h1 class="mt-5 mb-3">Сайты</h1>
<div class="table-responsive">
  <table class="table table-bordered table-hover text-nowrap">
    <tbody>
      <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Последняя проверка</th>
        <th>Код ответа</th>
      </tr>
      <?php foreach ($urls as $url): ?>
        <tr>
          <td><?= $url->id ?></td>
          <td>
            <a href="<?= $router->urlFor('urls.show', ['id' => $url->id]) ?>">
              <?= $url->name ?>
            </a>
          </td>
          <td><?= $url->created_at ?></td>
          <td><?= $url->status ?? '' ?></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
